// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSTPRjUPHz5WjBM6gMO-xO9fxudUTib5A',
    appId: '1:426093105095:web:8eabcc381af3c3d52813e2',
    messagingSenderId: '426093105095',
    projectId: 'hishaam-todo',
    authDomain: 'hishaam-todo.firebaseapp.com',
    storageBucket: 'hishaam-todo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxj2E6Tj3clgaTgrw1n7cXoiVdQwTCeEo',
    appId: '1:426093105095:android:b4d9b20a839371522813e2',
    messagingSenderId: '426093105095',
    projectId: 'hishaam-todo',
    storageBucket: 'hishaam-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbuOGuXK_b2Ckfu7hffixGLHSQ_Vam-UE',
    appId: '1:426093105095:ios:c138ca7f0ad6aba62813e2',
    messagingSenderId: '426093105095',
    projectId: 'hishaam-todo',
    storageBucket: 'hishaam-todo.appspot.com',
    iosClientId: '426093105095-89r840hqnls362ku666ta8mrb04bccue.apps.googleusercontent.com',
    iosBundleId: 'com.example.hishamTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbuOGuXK_b2Ckfu7hffixGLHSQ_Vam-UE',
    appId: '1:426093105095:ios:2f49bd039c39b5cf2813e2',
    messagingSenderId: '426093105095',
    projectId: 'hishaam-todo',
    storageBucket: 'hishaam-todo.appspot.com',
    iosClientId: '426093105095-boncb0amlb0f0ig1f722jcfker1jdsjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.hishamTodo.RunnerTests',
  );
}
